#!/bin/bash

FLAG=$3

# Rebuild tags only after branch checkout, not file checkout
if [[ "$FLAG" == "1" ]]; then
    if which ctags >/dev/null; then
        echo "Rebuilding tags after branch checkout..."
        git ls-files | ctags -f .tags --fields=+li --extra=+q -L -
    fi
fi
